name: Run Vitest on PRs

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest tests
        run: npm run test -- --coverage --run